
dagknows_curr_profile() {
  if [ -f ~/.dagknows/current_profile ]; then
    cat ~/.dagknows/current_profile
  fi
}

dagknows_curr_session() {
  if [ -f ~/.dagknows/current_session ]; then
    cat ~/.dagknows/current_session
  fi
}

dagknows_cli_blobfile() {
   SESSION=`dagknows_curr_session`
   PROFILE=`dagknows_curr_profile`
   BLOBFILE="$HOME/.dagknows/$PROFILE/sessions/$SESSION/cliblob"
   CMDFILE="$HOME/.dagknows/$PROFILE/sessions/$SESSION/commands"
   echo $BLOBFILE
}

dagknows_cmd_file() {
   SESSION=`dagknows_curr_session`
   PROFILE=`dagknows_curr_profile`
   BLOBFILE="$HOME/.dagknows/$PROFILE/sessions/$SESSION/cliblob"
   CMDFILE="$HOME/.dagknows/$PROFILE/sessions/$SESSION/commands"
   echo $CMDFILE
}

dagknows_start_session_script() {
   PID=`echo $$`
   MYPPID=`ps -o ppid= -p ${PID} | xargs`
   MYPCMD=`ps -o comm= -p ${MYPPID} | xargs`
   SESSION=`dagknows_curr_session`
   PROFILE=`dagknows_curr_profile`
   if [ "$SESSION" = "" -o "$PROFILE" = "" ]; then
     return
   fi
   BLOBFILE=`dagknows_cli_blobfile`
   CMDFILE=`dagknows_cmd_file`
   if [ "$MYPCMD" != "script" ]; then
      echo "DagKnows Shell Recording On: $SESSION to $BLOBFILE"
      touch $BLOBFILE
      script -a -q -F $BLOBFILE
   else
   fi
}

dagknows_preexec() {
   PID=`echo $$`
   MYPPID=`ps -o ppid= -p ${PID} | xargs`
   MYPCMD=`ps -o comm= -p ${MYPPID} | xargs`
   SESSION=`dagknows_curr_session`
   PROFILE=`dagknows_curr_profile`
   if [ "$SESSION" = "" -o "$PROFILE" = "" ]; then
     return
   fi

   BLOBFILE=`dagknows_cli_blobfile`
   CMDFILE=`dagknows_cmd_file`
   if [ "$MYPCMD" = "script" ]; then
      if [ ! -f "$BLOBFILE" ]; then
        echo "WARNING - Please start a new shell, script output file ($BLOBFILE) missing"
        if [ -f "$CMDFILE" ]; then
          mv $CMDFILE "${CMDFILE}.bak"
        fi
      else
        echo "PROMPT: " "'${(%%)PS1}'" " CMD: " $3  >> $CMDFILE
      fi
   fi
}

dagknows_precmd() {
  SESSION=`dagknows_curr_session`
  PROFILE=`dagknows_curr_profile`
  if [ "$SESSION" != "" -a "$PROFILE" != "" ]; then
    dk --profile=$PROFILE sessions flush $SESSION
  fi
}

preexec() {
  dagknows_preexec $*
}

precmd() {
  dagknows_precmd $*
}

dagknows_start_session_script

